#ifndef PANTHERA_PROFILE_HPP
#define PANTHERA_PROFILE_HPP

/*#include <optick.h>

#define PANTHERA_PROFILE_FUNCTION() OPTICK_EVENT();
#define PANTHERA_PROFILE_SCOPE(name) OPTICK_EVENT(name);
#define PANTHERA_PROFILE_SCOPE_FUNCTION() PANTHERA_PROFILE_SCOPE(__FUNCTION__)
#define PANTHERA_PROFILE_FRAME(name) OPTICK_FRAME(name);
#define PANTHERA_PROFILE_THREAD(name) OPTICK_THREAD(name);*/

#endif //PANTHERA_PROFILE_HPP
