name: CI

on: [push, pull_request, release]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Bazel Cache
        uses: actions/cache@v2
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
            key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-development
      - uses: actions/checkout@v2

      - name: Build Code
        run: bazel build ...